django_hh_project/hh_app/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'hh_app'

urlpatterns = [
	path('upload/',upload_form,name='upload_form'),
	path('uploader/',uploader,name='uploader'),
	path('look/<file_name>/',look,name='look'),

	path('', home, name="home"),
	path('create_bar/', create_bar, name='bar_form'),
	path('create_happy_hour/<int:bar_id>/', create_happy_hour, name='hh_form'),
	path('region/<int:pk>/', RegionDetail.as_view(), name='region_detail'),
	path('reviews/<int:pk>/update/',ReviewUpdate.as_view(), name='update_review'),
	path('reviews/create/',ReviewCreate.as_view(),name='create_review'),
	path('bars/<int:pk>/update/',BarUpdate.as_view(), name='update_bar'),
	path('happy_hours/<int:pk>/update/',HHUpdate.as_view(), name='update_hh'),
	path('search/', search_hhs ,name='search'),
	path('register/',register,name='register'),
	path('account/',account, name='account'),
	path('logout/', auth_views.LogoutView.as_view(template_name='hh_app/logout.html'), name='logout'),
	path('login/', auth_views.LoginView.as_view(template_name='hh_app/login.html'), name='login'),
	path('allbars/', display_all_bars, name='allbars'),
	path('mybars/', display_bars, name='mybars'),
	path('bars/<int:bar_id>/happy_hours', display_bars_happyhours, name='bar_hhs'),
	path('bars/<int:bar_id>/reviews', display_bars_reviews, name='bar_reviews'),
	path('reviews/history/',MyReviewsDisplay.as_view(), name='my_reviews'),
	path('happy_hours/<int:pk>/delete', HappyHourDelete.as_view(), name='hh_delete'),
	path('bars/<int:pk>/delete', BarDelete.as_view(), name='bar_delete'),
	path('reviews/<int:pk>/delete', ReviewDelete.as_view(), name='review_delete'),
	path('info/', project_info, name='project_info'),
	path('about/', project_about, name='project_about')
]

django_hh_project/hh_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('hh_app.api_urls')),
    path('', include('hh_app.urls')),
]

django_hh_project/hh_app/models.py
from django.core.validators import RegexValidator
from django.db import models

from django.contrib.auth.models import User


# Create your models here.
class Region(models.Model):
	region_name = models.CharField(max_length = 100)
	def __str__(self):
		return str(self.region_name)

class Feature(models.Model):
	feature_title = models.CharField(max_length = 100)
	description = models.CharField(max_length = 100)
	def __str__(self):
		return str(self.feature_title)

class Bar(models.Model):
	bar_name = models.CharField(max_length = 100)
	street_address = models.CharField(max_length = 100)
	phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
	phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # va
	manager = models.ForeignKey(User, on_delete = models.CASCADE)
	approved = models.BooleanField(default = False)
	region = models.ForeignKey(Region, on_delete = models.CASCADE)
	features = models.ManyToManyField(Feature, blank=True)
	def __str__(self):
		return str(self.bar_name) + ' ' + str(self.street_address)

class HappyHour(models.Model):
	day_of_week = models.CharField(max_length = 2)
	start_time = models.TimeField()
	end_time = models.TimeField()
	bar = models.ForeignKey(Bar, on_delete = models.CASCADE)
	drinks = models.BooleanField(default = False)
	food = models.BooleanField(default = False)
	menu_pdf = models.CharField(max_length = 100)
	def __str__(self):
		return str(self.bar.bar_name) + ': ' + str(self.day_of_week)
	def day(self):
		days = {'M':'Monday','T':'Tuesday','W':'Wednesday','Th':'Thursday','F':'Friday',
				'Sa':'Saturday','Su':'Sunday'}
		return days[self.day_of_week]


class Reviews(models.Model):
	reviewer = models.ForeignKey(User, on_delete = models.CASCADE)
	bar = models.ForeignKey(Bar, on_delete = models.CASCADE)
	star_count = models.IntegerField()
	review_text = models.TextField(null=True, blank=True)
	def __str__(self):
		return str(self.reviewer.username) + ': ' + str(self.bar) + ' - ' + str(self.star_count) + ' stars'


django_hh_project/hh_app/views.py
#=========================================================================================
#=========================================================================================
#==============================FOR FILE UPLOAD PURPOSES ONLY==============================
#=========================================================================================
#=========================================================================================

from google.cloud import storage
from google.cloud.storage import Blob
from werkzeug.utils import secure_filename
import io
import requests

def uploader(request):
	if request.method == 'POST':
		form = UploadFileForm(request.POST, request.FILES)
		if form.is_valid():
			file = request.FILES['file']
			bucket_name = "menus_happierhour"
			client = storage.Client()
			bucket = client.get_bucket(bucket_name)
			blob = bucket.blob(secure_filename(file.name))
			try:
				blob.upload_from_file(file.file)
				return JsonResponse({"success": True})
			except Exception as e:
				logging.exception(e)
				return JsonResponse({"success": False})
	return JsonResponse({'success':False})


def upload_form(request):
	return render(request=request,template_name='files/upload.html', context={'form':UploadFileForm()})
def look(request,file_name):
	try:
	# Reformat the filename using the bucket name fetched above
		bucket_name = "menus_happierhour"
		client = storage.Client()
		bucket = client.get_bucket(bucket_name)
		blob = bucket.blob(secure_filename(file_name))
		data = blob.download_as_string()	
		extension = secure_filename(file_name).rsplit('.', 1)[1]
		if extension == "png":
			return FileResponse(io.BytesIO(data),content_type='image/png')

		elif extension == 'pdf':
			return FileResponse(io.BytesIO(data),content_type='application/pdf')
		else:
			return FileResponse(io.BytesIO(data))
	except Exception as e: 
		return JsonResponse({'error': 'Could not find file {}'.format(file_name)})


#=========================================================================================
#=========================================================================================
#==============================ACTUAL APPLICATION VIEWS===================================
#=========================================================================================
#=========================================================================================

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q, Avg
from django.http import *
from django.shortcuts import *
from django.urls import reverse, reverse_lazy
from django.views import generic

from .models import *
from .forms import *

def home(request):
	if request.method == "GET":
		pass
	elif request.method == "POST":
		pass
	context_dict = {'somekey':'somevalue', 'otherkey':'othervalue'}
	return render(request = request,
				  template_name = "hh_app/home.html",
				  context = context_dict)


def register(request):
	if request.method == "POST":
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			#TODO: add messages to base template
			# messages.success(request, f'Your account has been created {username}!')
			#TODO: log user in
			return redirect(reverse('hh_app:login'))
	else:
		form = UserRegisterForm()
	return render(request, 'hh_app/register.html', {"form":form})

@login_required
def account(request):
	if request.method == "POST":
		u_form = UserUpdateForm(request.POST, instance=request.user)
		if u_form.is_valid():
			u_form.save()
			username=form.cleaned_data.get('username')
			messages.success(request, f'{username}, your account has been updated!')
			return redirect(reverse('hh_app:home'))
	else:
		u_form = UserUpdateForm(instance=request.user)
	context = {
		'u_form': u_form
	}
	return render(request, 'users/profile.html', context)

class RegionDetail(generic.DetailView):
	model = Region
	template_name = 'hh_app/region_detail.html'

class RegionUpdate():
	pass #Not Necessary: will only be edited by admin in dashboard

class FeatureUpdate():
	pass #Not Necessary. Changing features will only happen by admin.
	#NOTE: bar managers can change bar features in bar edit

class BarUpdate(UserPassesTestMixin, generic.UpdateView):
	#only manager can update
	model = Bar
	template_name = 'hh_app/bar_update.html'
	fields = ['bar_name','street_address','phone_number','region','features']
	success_url = reverse_lazy('hh_app:mybars')
	def test_func(self):
		bar_id = self.kwargs.get('pk')
		bar = Bar.objects.get(id=bar_id)
		return self.request.user == bar.manager

class HHUpdate(UserPassesTestMixin,generic.UpdateView):
	#only bar manager can update
	model = HappyHour
	template_name = 'hh_app/hh_update.html'
	fields = ['start_time','end_time','drinks','food','menu_pdf']
	def test_func(self):
		hh_id = self.kwargs.get('pk')
		hh = HappyHour.objects.get(id=hh_id)
		self.bar = hh.bar
		return self.request.user == hh.bar.manager
	def get_success_url(self):
		return reverse('hh_app:bar_hhs', kwargs={'bar_id': self.bar.id})

class ReviewUpdate(UserPassesTestMixin, generic.UpdateView):
	model = Reviews
	template_name = 'hh_app/review_update.html'
	fields = ['star_count','review_text']
	success_url = reverse_lazy('hh_app:my_reviews')
	def test_func(self): #The test to see if user is creator of review
		review_id = self.kwargs.get('pk')
		review = Reviews.objects.get(id=review_id)
		return review.reviewer == self.request.user

class ReviewCreate(LoginRequiredMixin,generic.CreateView):
	model = Reviews
	fields = ['bar','star_count','review_text']
	template_name = 'hh_app/review_create.html'
	success_url = reverse_lazy('hh_app:home')
	def form_valid(self,form):
		form.instance.reviewer = self.request.user
		return super().form_valid(form)

class HappyHourDelete(UserPassesTestMixin, generic.DeleteView):
	model = HappyHour
	template_name = 'hh_app/hh_delete.html'
	def test_func(self):
		self.bar = HappyHour.objects.get(id = self.kwargs.get('pk')).bar
		return self.bar.manager==self.request.user
	def get_success_url(self):
		return reverse('hh_app:bar_hhs', kwargs={'bar_id': self.bar.id})

class BarDelete(UserPassesTestMixin, generic.DeleteView):
	model = Bar
	template_name = 'hh_app/bar_delete.html'
	def test_func(self):
		bar = Bar.objects.get(id = self.kwargs.get('pk'))
		return bar.manager==self.request.user
	def get_success_url(self):
		return reverse('hh_app:mybars')

class ReviewDelete(UserPassesTestMixin, generic.DeleteView):
	model = Reviews
	template_name = 'hh_app/review_delete.html'
	def test_func(self):
		review = Reviews.objects.get(id = self.kwargs.get('pk'))
		return review.reviewer==self.request.user
	def get_success_url(self):
		return reverse('hh_app:my_reviews')

@login_required
def create_bar(request):
	if request.method == 'POST':
		form = CreateBarForm(request.POST)

		if form.is_valid():
			bar = form.save(commit=False)
			bar.manager = request.user
			bar.approved = False
			bar.save()
			return redirect(reverse('hh_app:mybars'))

	else:
		form = CreateBarForm()

	return render(request, 'hh_app/bar_create.html', {'form': form})

@login_required
def create_happy_hour(request, bar_id):
	
	bar = Bar.objects.get(id=bar_id)
	
	if bar.manager != request.user:
		return HttpResponseForbidden()

	if request.method == 'POST':
		form = CreateHappyHour(request.POST)

		if form.is_valid():
			for day in form.cleaned_data['weekdays']:
				hh = HappyHour(day_of_week=day, bar = bar)
				form = CreateHappyHour(request.POST, instance=hh)
				form.save()

			return redirect(reverse('hh_app:bar_hhs', kwargs={'bar_id': bar.id}))

	else:
		form = CreateHappyHour()

	return render(request, 'hh_app/hh_create.html', {'form': form})

def search_hhs(request):
	if request.method == 'POST':
		form = HHFilterForm(request.POST)
		if form.is_valid():
			day = form.cleaned_data['day']
			#time
			region = form.cleaned_data['region']
			features = form.cleaned_data['features']
			star_count = form.cleaned_data['star_count']
			drinks = form.cleaned_data['drinks']
			food = form.cleaned_data['food']

			qualifying_hhs = HappyHour.objects.filter(day_of_week = day)
			if drinks:
				qualifying_hhs = qualifying_hhs.filter(drinks=True)
			if food:
				qualifying_hhs = qualifying_hhs.filter(food=True)

			qualifying_bars = Bar.objects.filter(approved=True)
			if star_count:
				qualifying_bars = Bar.objects.annotate(ave_stars = Avg('reviews__star_count')).filter(ave_stars__gte = star_count)
			if region:
				qualifying_bars = Bar.objects.filter(region = region)
			for feature in features:
				f_bars = (Feature.objects.get(id = feature.id)).bar_set.all()
				qualifying_bars = qualifying_bars & f_bars

			final_hhs = list(qualifying_hhs.filter(Q(bar__in=list(qualifying_bars))).all())

			return render(request,'hh_app/filtered_hhs.html',{'hh_list':final_hhs})

	else:
		form = HHFilterForm()
	return render(request,'hh_app/filter.html',{'form':form})


class MyReviewsDisplay(LoginRequiredMixin,generic.ListView):
	model = Reviews
	template_name = 'hh_app/my_reviews_display.html'
	def get_queryset(self):
		return self.request.user.reviews_set.all()

def display_bars(request):
	return render(request, 'hh_app/display_bars.html', {'bars': request.user.bar_set.all()})

def display_bars_happyhours(request, bar_id):
	bar_obj = Bar.objects.get(id=bar_id)
	return render(request, 'hh_app/display_hhs.html', {'bar': bar_obj, 'hhs': bar_obj.happyhour_set.all().order_by('day_of_week')})

def display_bars_reviews(request, bar_id):
	bar_obj = Bar.objects.get(id=bar_id)

django_hh_project/hh_app/templates/hh_app/bar_delete.html
{%extends 'hh_app/base.html'%}

{% block content %}

<form method="post">{% csrf_token %}
   <p class="alert alert-dismissible alert-danger">Are you sure you want to delete "{{ object.bar_name }} at {{ object.street_address }}"?</p>
   <input type="submit" class="btn btn-danger" value="Delete">
</form>

{% endblock %}

django_hh_project/hh_app/templates/hh_app/base.html
{% load static %}

<head>
  <link rel="stylesheet" href="{% static 'hh_app/bootstrap.css' %}">
</head>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
  <a class="navbar-brand" href="{% url 'hh_app:home' %}">Happier Hour</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'hh_app:home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'hh_app:search' %}">Find a Happy Hour</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'hh_app:allbars' %}">See All Bars</a>
      </li>
      {% if user.bar_set.all|length %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'hh_app:mybars' %}">Manage Bars</a>
        </li>
      {% else %}
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hh_app:bar_form' %}">Add your Bar</a>
          </li>
        {% endif %}
      {% endif %}
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'hh_app:create_review' %}">Create a Review</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'hh_app:logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'hh_app:login' %}">Login</a>
        </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'hh_app:project_info' %}">Project Info</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'hh_app:project_about' %}">About US</a>
      </li>
    </ul>
  </div>
</nav>

{%block info%}
{%endblock%}

<div class="ourcontent">
  {% block content%}
  {% endblock %}
</div>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

django_hh_project/hh_app/templates/hh_app/base_backup.html
<!-- {% load static %}

<h1>
	This is our header from base
</h1>

<div>
	{% block content %}
	<h1>
		You should not see this
	</h1>
	{% endblock %}
</div>
https://bootswatch.com/4/lux/bootstrap.min.css -->
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Pricing example for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/pricing/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="pricing.css" rel="stylesheet">
  </head>

  <body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">Company name</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="#">Features</a>
        <a class="p-2 text-dark" href="#">Enterprise</a>
        <a class="p-2 text-dark" href="#">Support</a>
        <a class="p-2 text-dark" href="#">Pricing</a>
      </nav>
      <a class="btn btn-outline-primary" href="#">Sign up</a>
    </div>

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Pricing</h1>
      <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It's built with default Bootstrap components and utilities with little customization.</p>
    </div>

    <div class="container">
      <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Free</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$0 <small class="text-muted">/ mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>10 users included</li>
              <li>2 GB of storage</li>
              <li>Email support</li>
              <li>Help center access</li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button>
          </div>
        </div>
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Pro</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$15 <small class="text-muted">/ mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>20 users included</li>
              <li>10 GB of storage</li>
              <li>Priority email support</li>
              <li>Help center access</li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-primary">Get started</button>
          </div>
        </div>
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Enterprise</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>30 users included</li>
              <li>15 GB of storage</li>
              <li>Phone and email support</li>
              <li>Help center access</li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-primary">Contact us</button>
          </div>
        </div>
      </div>

      <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-12 col-md">
            <img class="mb-2" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
            <small class="d-block mb-3 text-muted">&copy; 2017-2018</small>
          </div>
          <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Cool stuff</a></li>
              <li><a class="text-muted" href="#">Random feature</a></li>
              <li><a class="text-muted" href="#">Team feature</a></li>
              <li><a class="text-muted" href="#">Stuff for developers</a></li>
              <li><a class="text-muted" href="#">Another one</a></li>
              <li><a class="text-muted" href="#">Last time</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Resource</a></li>
              <li><a class="text-muted" href="#">Resource name</a></li>
              <li><a class="text-muted" href="#">Another resource</a></li>
              <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Team</a></li>
              <li><a class="text-muted" href="#">Locations</a></li>
              <li><a class="text-muted" href="#">Privacy</a></li>
              <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
          </div>
        </div>
      </footer>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  </body>
</html>

django_hh_project/hh_app/templates/hh_app/create.html
{%extends 'hh_app/base.html'%}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form | linebreaks}}
    <input type="submit" value="Submit">
</form>
{% endblock %}

django_hh_project/hh_app/templates/hh_app/create_bar.html
{%extends 'hh_app/base.html'%}

{% block content %}
<form action="/created-bar/" method="post">
    {% csrf_token %}
    {{ form | linebreaks}}
    <input type="submit" value="Submit">
</form>
{% endblock %}

django_hh_project/hh_app/templates/hh_app/display_all_bars.html
{%extends 'hh_app/base.html'%}

{% block content %}
<h3>All Bars</h3>
<br>

<div class="columns">
{% for b in bars %}
	<div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
	  <div class="card-header">{{ b.bar_name }}</div>
	  <div class="card-body">
	    <h4 class="card-title">{%for hh in b.happyhour_set.all %}{{hh.day_of_week}} {%endfor%}</h4>
	    {% if b.happyhour_set.all|length == 0 %}
	    <h4 class="card-title">No Happy Hours Currently</h4>
	    {% endif %}
	    <p class="card-text"><b style="color: #4BBF73">{{ b.region }}</b> <br> {{ b.street_address }} <br> {{ b.avg_count }}<br></p>
	    <button type="button" class="btn btn-success" onclick=window.location.href="{% url 'hh_app:bar_hhs' b.id%}">View HappyHours</button>
	  </div>
	</div>
{% endfor %}
</div>

{% endblock %}

django_hh_project/hh_app/templates/hh_app/display_bar_reviews.html
{%extends 'hh_app/base.html'%}

{% block content %}
<h3>{{bar.bar_name}}'s Reviews</h3>
<br>
<table class='table'>
	<tr>
		<th>Review By</th>
		<th>Star Count</th>
		<th>Review Text</th>
	</tr>
	{% for r in reviews %}
	<tr>
		<td>
			{{r.reviewer.first_name}}
		</td>
		<td>
			{{r.star_count}}
		</td>
		<td>
			{{r.review_text}}
		</td>
	</tr>
	{% endfor %}
</table>
{% endblock %}

django_hh_project/hh_app/templates/hh_app/filtered_hhs.html
{%extends 'hh_app/home.html'%}

{%block content%}
<h3>Happy Hour Results</h3>
<br>

<div class="container ">
	
	{% for hh in hh_list %}
		<div class="card text-white bg-primary mb-3" style="">
		  <div class="card-header">{{hh.day}} from {{hh.start_time}} to {{hh.end_time}}</div>
		  <div class="card-body">
		    <h2 class="card-title">{{hh.bar.bar_name}} - {{hh.bar.region.region_name}}</h4>
		    <h4 class="card-title">{{hh.bar.street_address}}</h2>
		    <p class="card-text">Drinks? {% if hh.drinks %}YES{%else%}NO{%endif%}</p>
		    <p class="card-text">Food? {% if hh.food %}YES{%else%}NO{%endif%}</p>
		    {% for feature in hh.bar.features.all%}
		    <p class="card-text">{{feature.feature_title}} - {{feature.description}}</p>
		    {% endfor %}
		    <div>
		    	<button type="button" class="btn btn-secondary" onclick=window.location.href="{{hh.menu_pdf}}">Menu</button>
		    	<button type="button" class="btn btn-success" onclick=window.location.href="{% url 'hh_app:bar_reviews' hh.bar.id %}">See all Reviews</button>	
		    </div>
		  </div>
		</div>
	{% endfor %}

</div>
{%endblock%}

django_hh_project/hh_app/templates/hh_app/home.html
{% extends 'hh_app/base.html' %}

{% block content %}
<h3>Home page</h3>

<p>Find happy hours near you!</p>

{% if not user.is_authenticated %}
<p>If your a new user, register <a href="{% url 'hh_app:register' %}">HERE</a>!</p>
{% endif %}

{% endblock %}